/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.9.3 */

#include "messages.pb.h"

const char GetPublicKey_coin_name_default[21] = "Bitcoin";
const char GetAddress_coin_name_default[21] = "Bitcoin";
const InputScriptType GetAddress_script_type_default = InputScriptType_SPENDADDRESS;
const char LoadDevice_language_default[17] = "english";
const uint32_t ResetDevice_strength_default = 256u;
const char ResetDevice_language_default[17] = "english";
const char RecoveryDevice_language_default[17] = "english";
const char SignMessage_coin_name_default[21] = "Bitcoin";
const InputScriptType SignMessage_script_type_default = InputScriptType_SPENDADDRESS;
const char VerifyMessage_coin_name_default[21] = "Bitcoin";
const char SignTx_coin_name_default[21] = "Bitcoin";
const uint32_t SignTx_version_default = 1u;
const uint32_t SignTx_lock_time_default = 0u;


const pb_field_t Initialize_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t GetFeatures_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t Features_fields[21] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, STATIC  , FIRST, Features, vendor, vendor, 0),
    PB_FIELD2(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Features, major_version, vendor, 0),
    PB_FIELD2(  3, UINT32  , OPTIONAL, STATIC  , OTHER, Features, minor_version, major_version, 0),
    PB_FIELD2(  4, UINT32  , OPTIONAL, STATIC  , OTHER, Features, patch_version, minor_version, 0),
    PB_FIELD2(  5, BOOL    , OPTIONAL, STATIC  , OTHER, Features, bootloader_mode, patch_version, 0),
    PB_FIELD2(  6, STRING  , OPTIONAL, STATIC  , OTHER, Features, device_id, bootloader_mode, 0),
    PB_FIELD2(  7, BOOL    , OPTIONAL, STATIC  , OTHER, Features, pin_protection, device_id, 0),
    PB_FIELD2(  8, BOOL    , OPTIONAL, STATIC  , OTHER, Features, passphrase_protection, pin_protection, 0),
    PB_FIELD2(  9, STRING  , OPTIONAL, STATIC  , OTHER, Features, language, passphrase_protection, 0),
    PB_FIELD2( 10, STRING  , OPTIONAL, STATIC  , OTHER, Features, label, language, 0),
    PB_FIELD2( 11, MESSAGE , REPEATED, STATIC  , OTHER, Features, coins, label, &CoinType_fields),
    PB_FIELD2( 12, BOOL    , OPTIONAL, STATIC  , OTHER, Features, initialized, coins, 0),
    PB_FIELD2( 13, BYTES   , OPTIONAL, STATIC  , OTHER, Features, revision, initialized, 0),
    PB_FIELD2( 14, BYTES   , OPTIONAL, STATIC  , OTHER, Features, bootloader_hash, revision, 0),
    PB_FIELD2( 15, BOOL    , OPTIONAL, STATIC  , OTHER, Features, imported, bootloader_hash, 0),
    PB_FIELD2( 16, BOOL    , OPTIONAL, STATIC  , OTHER, Features, pin_cached, imported, 0),
    PB_FIELD2( 17, BOOL    , OPTIONAL, STATIC  , OTHER, Features, passphrase_cached, pin_cached, 0),
    PB_FIELD2( 18, BOOL    , OPTIONAL, STATIC  , OTHER, Features, firmware_present, passphrase_cached, 0),
    PB_FIELD2( 19, BOOL    , OPTIONAL, STATIC  , OTHER, Features, needs_backup, firmware_present, 0),
    PB_FIELD2( 20, UINT32  , OPTIONAL, STATIC  , OTHER, Features, flags, needs_backup, 0),
    PB_LAST_FIELD
};

const pb_field_t ClearSession_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t ApplySettings_fields[5] = {
    // not implemented
    PB_LAST_FIELD
};

const pb_field_t ApplyFlags_fields[2] = {
    PB_FIELD2(  1, UINT32  , OPTIONAL, STATIC  , FIRST, ApplyFlags, flags, flags, 0),
    PB_LAST_FIELD
};

const pb_field_t ChangePin_fields[2] = {
    PB_FIELD2(  1, BOOL    , OPTIONAL, STATIC  , FIRST, ChangePin, remove, remove, 0),
    PB_LAST_FIELD
};

const pb_field_t Ping_fields[5] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, STATIC  , FIRST, Ping, message, message, 0),
    PB_FIELD2(  2, BOOL    , OPTIONAL, STATIC  , OTHER, Ping, button_protection, message, 0),
    PB_FIELD2(  3, BOOL    , OPTIONAL, STATIC  , OTHER, Ping, pin_protection, button_protection, 0),
    PB_FIELD2(  4, BOOL    , OPTIONAL, STATIC  , OTHER, Ping, passphrase_protection, pin_protection, 0),
    PB_LAST_FIELD
};

const pb_field_t Success_fields[2] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, STATIC  , FIRST, Success, message, message, 0),
    PB_LAST_FIELD
};

const pb_field_t Failure_fields[3] = {
    PB_FIELD2(  1, ENUM    , OPTIONAL, STATIC  , FIRST, Failure, code, code, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, STATIC  , OTHER, Failure, message, code, 0),
    PB_LAST_FIELD
};

const pb_field_t ButtonRequest_fields[3] = {
    PB_FIELD2(  1, ENUM    , OPTIONAL, STATIC  , FIRST, ButtonRequest, code, code, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, STATIC  , OTHER, ButtonRequest, data, code, 0),
    PB_LAST_FIELD
};

const pb_field_t ButtonAck_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t PinMatrixRequest_fields[2] = {
    PB_FIELD2(  1, ENUM    , OPTIONAL, STATIC  , FIRST, PinMatrixRequest, type, type, 0),
    PB_LAST_FIELD
};

const pb_field_t PinMatrixAck_fields[2] = {
    PB_FIELD2(  1, STRING  , REQUIRED, STATIC  , FIRST, PinMatrixAck, pin, pin, 0),
    PB_LAST_FIELD
};

const pb_field_t Cancel_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t PassphraseRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t PassphraseAck_fields[2] = {
    PB_FIELD2(  1, STRING  , REQUIRED, STATIC  , FIRST, PassphraseAck, passphrase, passphrase, 0),
    PB_LAST_FIELD
};

const pb_field_t GetEntropy_fields[2] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC  , FIRST, GetEntropy, size, size, 0),
    PB_LAST_FIELD
};

const pb_field_t Entropy_fields[2] = {
    PB_FIELD2(  1, BYTES   , REQUIRED, STATIC  , FIRST, Entropy, entropy, entropy, 0),
    PB_LAST_FIELD
};

const pb_field_t GetPublicKey_fields[5] = {
    PB_FIELD2(  1, UINT32  , REPEATED, STATIC  , FIRST, GetPublicKey, address_n, address_n, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, STATIC  , OTHER, GetPublicKey, ecdsa_curve_name, address_n, 0),
    PB_FIELD2(  3, BOOL    , OPTIONAL, STATIC  , OTHER, GetPublicKey, show_display, ecdsa_curve_name, 0),
    PB_FIELD2(  4, STRING  , OPTIONAL, STATIC  , OTHER, GetPublicKey, coin_name, show_display, &GetPublicKey_coin_name_default),
    PB_LAST_FIELD
};

const pb_field_t PublicKey_fields[3] = {
    PB_FIELD2(  1, MESSAGE , REQUIRED, STATIC  , FIRST, PublicKey, node, node, &HDNodeType_fields),
    PB_FIELD2(  2, STRING  , OPTIONAL, STATIC  , OTHER, PublicKey, xpub, node, 0),
    PB_LAST_FIELD
};

const pb_field_t GetAddress_fields[6] = {
    PB_FIELD2(  1, UINT32  , REPEATED, STATIC  , FIRST, GetAddress, address_n, address_n, 0),
    PB_FIELD2(  2, STRING  , OPTIONAL, STATIC  , OTHER, GetAddress, coin_name, address_n, &GetAddress_coin_name_default),
    PB_FIELD2(  3, BOOL    , OPTIONAL, STATIC  , OTHER, GetAddress, show_display, coin_name, 0),
    PB_FIELD2(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, GetAddress, multisig, show_display, &MultisigRedeemScriptType_fields),
    PB_FIELD2(  5, ENUM    , OPTIONAL, STATIC  , OTHER, GetAddress, script_type, multisig, &GetAddress_script_type_default),
    PB_LAST_FIELD
};

const pb_field_t Address_fields[2] = {
    PB_FIELD2(  1, STRING  , REQUIRED, STATIC  , FIRST, Address, address, address, 0),
    PB_LAST_FIELD
};

const pb_field_t WipeDevice_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t LoadDevice_fields[9] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, STATIC  , FIRST, LoadDevice, mnemonic, mnemonic, 0),
    PB_FIELD2(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, LoadDevice, node, mnemonic, &HDNodeType_fields),
    PB_FIELD2(  3, STRING  , OPTIONAL, STATIC  , OTHER, LoadDevice, pin, node, 0),
    PB_FIELD2(  4, BOOL    , OPTIONAL, STATIC  , OTHER, LoadDevice, passphrase_protection, pin, 0),
    PB_FIELD2(  5, STRING  , OPTIONAL, STATIC  , OTHER, LoadDevice, language, passphrase_protection, &LoadDevice_language_default),
    PB_FIELD2(  6, STRING  , OPTIONAL, STATIC  , OTHER, LoadDevice, label, language, 0),
    PB_FIELD2(  7, BOOL    , OPTIONAL, STATIC  , OTHER, LoadDevice, skip_checksum, label, 0),
    PB_FIELD2(  8, UINT32  , OPTIONAL, STATIC  , OTHER, LoadDevice, u2f_counter, skip_checksum, 0),
    PB_LAST_FIELD
};

const pb_field_t ResetDevice_fields[9] = {
    PB_FIELD2(  1, BOOL    , OPTIONAL, STATIC  , FIRST, ResetDevice, display_random, display_random, 0),
    PB_FIELD2(  2, UINT32  , OPTIONAL, STATIC  , OTHER, ResetDevice, strength, display_random, &ResetDevice_strength_default),
    PB_FIELD2(  3, BOOL    , OPTIONAL, STATIC  , OTHER, ResetDevice, passphrase_protection, strength, 0),
    PB_FIELD2(  4, BOOL    , OPTIONAL, STATIC  , OTHER, ResetDevice, pin_protection, passphrase_protection, 0),
    PB_FIELD2(  5, STRING  , OPTIONAL, STATIC  , OTHER, ResetDevice, language, pin_protection, &ResetDevice_language_default),
    PB_FIELD2(  6, STRING  , OPTIONAL, STATIC  , OTHER, ResetDevice, label, language, 0),
    PB_FIELD2(  7, UINT32  , OPTIONAL, STATIC  , OTHER, ResetDevice, u2f_counter, label, 0),
    PB_FIELD2(  8, BOOL    , OPTIONAL, STATIC  , OTHER, ResetDevice, skip_backup, u2f_counter, 0),
    PB_LAST_FIELD
};

const pb_field_t BackupDevice_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t EntropyRequest_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t EntropyAck_fields[2] = {
    PB_FIELD2(  1, BYTES   , OPTIONAL, STATIC  , FIRST, EntropyAck, entropy, entropy, 0),
    PB_LAST_FIELD
};

const pb_field_t RecoveryDevice_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t WordRequest_fields[2] = {
    PB_FIELD2(  1, ENUM    , OPTIONAL, STATIC  , FIRST, WordRequest, type, type, 0),
    PB_LAST_FIELD
};

const pb_field_t WordAck_fields[2] = {
    PB_FIELD2(  1, STRING  , REQUIRED, STATIC  , FIRST, WordAck, word, word, 0),
    PB_LAST_FIELD
};

const pb_field_t SignMessage_fields[5] = {
    PB_FIELD2(  1, UINT32  , REPEATED, STATIC  , FIRST, SignMessage, address_n, address_n, 0),
    PB_FIELD2(  2, BYTES   , REQUIRED, STATIC  , OTHER, SignMessage, message, address_n, 0),
    PB_FIELD2(  3, STRING  , OPTIONAL, STATIC  , OTHER, SignMessage, coin_name, message, &SignMessage_coin_name_default),
    PB_FIELD2(  4, ENUM    , OPTIONAL, STATIC  , OTHER, SignMessage, script_type, coin_name, &SignMessage_script_type_default),
    PB_LAST_FIELD
};

const pb_field_t VerifyMessage_fields[5] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, STATIC  , FIRST, VerifyMessage, address, address, 0),
    PB_FIELD2(  2, BYTES   , OPTIONAL, STATIC  , OTHER, VerifyMessage, signature, address, 0),
    PB_FIELD2(  3, BYTES   , OPTIONAL, STATIC  , OTHER, VerifyMessage, message, signature, 0),
    PB_FIELD2(  4, STRING  , OPTIONAL, STATIC  , OTHER, VerifyMessage, coin_name, message, &VerifyMessage_coin_name_default),
    PB_LAST_FIELD
};

const pb_field_t MessageSignature_fields[3] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, STATIC  , FIRST, MessageSignature, address, address, 0),
    PB_FIELD2(  2, BYTES   , OPTIONAL, STATIC  , OTHER, MessageSignature, signature, address, 0),
    PB_LAST_FIELD
};

const pb_field_t SignTx_fields[6] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC  , FIRST, SignTx, outputs_count, outputs_count, 0),
    PB_FIELD2(  2, UINT32  , REQUIRED, STATIC  , OTHER, SignTx, inputs_count, outputs_count, 0),
    PB_FIELD2(  3, STRING  , OPTIONAL, STATIC  , OTHER, SignTx, coin_name, inputs_count, &SignTx_coin_name_default),
    PB_FIELD2(  4, UINT32  , OPTIONAL, STATIC  , OTHER, SignTx, version, coin_name, &SignTx_version_default),
    PB_FIELD2(  5, UINT32  , OPTIONAL, STATIC  , OTHER, SignTx, lock_time, version, &SignTx_lock_time_default),
    PB_LAST_FIELD
};

const pb_field_t TxRequest_fields[4] = {
    PB_FIELD2(  1, ENUM    , OPTIONAL, STATIC  , FIRST, TxRequest, request_type, request_type, 0),
    PB_FIELD2(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, TxRequest, details, request_type, &TxRequestDetailsType_fields),
    PB_FIELD2(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, TxRequest, serialized, details, &TxRequestSerializedType_fields),
    PB_LAST_FIELD
};

const pb_field_t TxAck_fields[2] = {
    PB_FIELD2(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, TxAck, tx, tx, &TransactionType_fields),
    PB_LAST_FIELD
};

const pb_field_t SignIdentity_fields[5] = {
    PB_FIELD2(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, SignIdentity, identity, identity, &IdentityType_fields),
    PB_FIELD2(  2, BYTES   , OPTIONAL, STATIC  , OTHER, SignIdentity, challenge_hidden, identity, 0),
    PB_FIELD2(  3, STRING  , OPTIONAL, STATIC  , OTHER, SignIdentity, challenge_visual, challenge_hidden, 0),
    PB_FIELD2(  4, STRING  , OPTIONAL, STATIC  , OTHER, SignIdentity, ecdsa_curve_name, challenge_visual, 0),
    PB_LAST_FIELD
};

const pb_field_t SignedIdentity_fields[4] = {
    PB_FIELD2(  1, STRING  , OPTIONAL, STATIC  , FIRST, SignedIdentity, address, address, 0),
    PB_FIELD2(  2, BYTES   , OPTIONAL, STATIC  , OTHER, SignedIdentity, public_key, address, 0),
    PB_FIELD2(  3, BYTES   , OPTIONAL, STATIC  , OTHER, SignedIdentity, signature, public_key, 0),
    PB_LAST_FIELD
};

const pb_field_t GetECDHSessionKey_fields[4] = {
    PB_FIELD2(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, GetECDHSessionKey, identity, identity, &IdentityType_fields),
    PB_FIELD2(  2, BYTES   , OPTIONAL, STATIC  , OTHER, GetECDHSessionKey, peer_public_key, identity, 0),
    PB_FIELD2(  3, STRING  , OPTIONAL, STATIC  , OTHER, GetECDHSessionKey, ecdsa_curve_name, peer_public_key, 0),
    PB_LAST_FIELD
};

const pb_field_t ECDHSessionKey_fields[2] = {
    PB_FIELD2(  1, BYTES   , OPTIONAL, STATIC  , FIRST, ECDHSessionKey, session_key, session_key, 0),
    PB_LAST_FIELD
};


